version: "2.1"

services:

  identity-service:
    build: ../../SwifttParcel.Services.Identity
    container_name: apa/identity-service
    restart: unless-stopped
    ports:
      - 6001:80
    networks:
      - swiftparcel

  availability-service:
    build: ../../SwiftParcel.Services.Availability
    container_name: apa/availability-service
    restart: unless-stopped
    ports:
      - 6002:80 
    networks:
      - swiftparcel
  web:
    build: ../../SwiftParcel.Web
    container_name: apa/swiftparcel-web
    restart: unless-stopped
    ports:
      - 3001:80 
    networks:
      - swiftparcel


networks:
  swiftparcel:
    name: swiftparcel-network
    external: true