version: "2.1"

services:

 api-gateway:
    build: ../../SwifttParcel.API.Gateway
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker # TODO: Add this file
    ports:
      - 5000:80
    networks:
      - pacco

  identity-service:
    build: ../../SwifttParcel.Services.Identity
    container_name: apa/identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - swiftparcel

  availability-service:
    build: ../../SwiftParcel.Services.Availability
    container_name: apa/availability-service
    restart: unless-stopped
    ports:
      - 5001:80 
    networks:
      - swiftparcel
  web:
    build: ../../SwiftParcel.Web
    container_name: apa/swiftparcel-web
    restart: unless-stopped
    ports:
      - 3001:80 
    networks:
      - swiftparcel
  
  customers-service:
    build: ../../SwiftParcel.Services.Customers
    container_name: customers-service
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - swiftparcel

  deliveries-service:
    build: ../../SwiftParcel.Services.Deliveries
    container_name: deliveries-service
    restart: unless-stopped
    ports:
      - 5003:80
    networks:
      - swiftparcel

  orders-service:
    build: ../../SwiftParcel.Services.Orders
    container_name: orders-service
    restart: unless-stopped
    ports:
      - 5006:80
    networks:
      - swiftparcel

  parcels-service:
    build: ../../SwiftParcel.Services.Parcels
    container_name: parcels-service
    restart: unless-stopped
    ports:
      - 5007:80
    networks:
      - swiftparcel

  pricing-service:
    build: ../../SwiftParcel.Services.Pricing
    container_name: pricing-service
    restart: unless-stopped
    ports:
      - 5008:80
    networks:
      - swiftparcel

networks:
  swiftparcel:
    name: swiftparcel-network
    external: true