name: Sync to Azure DevOps Repository

on:
  push:
    branches:
      - '*'

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      AZURE_DEVOPS_PAT: ${{ secrets.AZUREDEVOPSPAT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # Fetch all branches

      - name: Configuring git
        run: |
          git config --global user.email "voznesenskijandrej5@gmail.com"
          git config --global user.name "Andrii Voznesenskyi"

      - name: Adding Azure DevOps remote repository
        run: |
          git remote add azure https://01174367:$AZURE_DEVOPS_PAT@dev.azure.com/dotNetAPA/CurrierHub/_git/courier_app.git

      - name: Fetching from Azure DevOps
        run: |
          git fetch azure  --depth=2147483647

      - name: Pushing all branches to Azure DevOps
        run: |
          for branch in $(git branch -r | grep -v 'azure/' | sed 's/origin\///'); do
            git push azure $branch:$branch --force
          done
