name: Sync to Azure DevOps Repository

on:
  push:
    branches:
      - '*'

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Execute Git Commands
        run: |
          echo " - [ ] Configuring git..."
          echo " - [ ] Adding Azure DevOps remote repository..."
          git remote add azure https://dev.azure.com/dotNetAPA/CurrierHub/_git/courier_app.git
          echo " - [ ] Fetching from Azure DevOps..."
          git fetch azure
          echo " - [ ] Pushing to Azure DevOps main branch..."
          git push azure HEAD:main --force
        env:
          AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AzureDevOpsPAT }}
